# Generated by Django 4.1.7 on 2023-04-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('libro_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('entrada', models.TextField(null=True)),
                ('tipo_autor', models.CharField(max_length=255, null=True)),
                ('autor', models.CharField(max_length=255, null=True)),
                ('otros_autores', models.TextField(null=True)),
                ('edicion', models.CharField(max_length=255, null=True)),
                ('serie', models.CharField(max_length=255, null=True)),
                ('notas', models.TextField(null=True)),
                ('anno_pub', models.CharField(max_length=255, null=True)),
                ('mencion_resp', models.TextField(null=True)),
                ('cod_domicilio', models.CharField(max_length=255, null=True)),
                ('isbn', models.CharField(max_length=255, null=True)),
                ('dewey', models.CharField(max_length=255, null=True)),
                ('evento', models.CharField(max_length=255, null=True)),
                ('otros_eventos', models.CharField(max_length=255, null=True)),
                ('publicacion', models.CharField(max_length=255, null=True)),
                ('colacion', models.CharField(max_length=255, null=True)),
                ('otros_titulos', models.CharField(max_length=255, null=True)),
                ('folleto', models.CharField(max_length=255, null=True)),
                ('referencia', models.CharField(max_length=255, null=True)),
                ('letras_ent', models.CharField(max_length=255, null=True)),
                ('letra_titulo', models.CharField(max_length=255, null=True)),
                ('clasif', models.CharField(max_length=255, null=True)),
                ('idioma', models.CharField(max_length=255, null=True)),
                ('pais', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
