# Generated by Django 4.1.7 on 2023-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
    ]
