# Generated by Django 4.1.7 on 2023-04-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEjemplar',
            fields=[
                ('estado_ejemplar_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_ejemplar',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('ejemplar_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_barras', models.CharField(max_length=20, null=True)),
                ('subdivision1', models.CharField(max_length=100, null=True)),
                ('subdivision2', models.CharField(max_length=100, null=True)),
                ('no_ingreso', models.CharField(max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('ubicacion', models.CharField(max_length=100, null=True)),
                ('via_adq', models.CharField(max_length=100, null=True)),
                ('procedencia', models.CharField(max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'db_table': 'ejemplar',
            },
        ),
    ]
